---
title: "Transformando data.frames"
author: "Everton da Rosa"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

Exemplos de transformações e outras operações com data.frames e objetos equivalentes.

## data.frame long -> wide

Transforma um data.frame do formato longo (long) para o formato largo (wide)

```{r}
# data.frame de exemplo
df_long <- data.frame(
  name = c("John", "Mary", "Paul", "John", "Mary", "Paul"),
  year = c(2021, 2021, 2021, 2022, 2022, 2022),
  value = c(100, 105, 90, 110, 120, 100)
)
df_long
```

```{r}
df_wide <- spread(df_long, year, value)
df_wide
```

## data.frame wide -> long

Transforma um data.frame do formato largo (wide) para o formato longo (long)

```{r}
# data.frame de exemplo
df_wide <- data.frame(
  name = c("John", "Mary", "Paul"),
  "2021" = c(100, 105, 90),
  "2022" = c(110, 120, 100)
)
df_wide
```

```{r}
df_long <- gather(df_wide, "year", "value", 2:3)
df_long
```